apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: devopsproject1-secret
  namespace: default
spec:
  encryptedData:
    password: AgBJx6e...YourLongSealedSecretString...0q==    # <-- This will be the long encrypted string produced by kubeseal
  template:
    type: Opaque
    metadata:
      name: devopsproject1-secret
      namespace: default
