hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
